PR for html css branch
KALUNGI-J-BOBSON/Hello_World_Project pull request #1
Opened 2022-12-01 14:35 UTC by KALUNGI-J-BOBSON

2022-12-01 16:19 UTC, jerryowusu requested changes
Hi @KALUNGI-J-BOBSON , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![no-we-were-so-close-pauline-turner-brooks](https://user-images.githubusercontent.com/65233860/205104100-ce293265-859d-4afc-9a97-9f0090259580.gif)


## Highlights
Followed github flow :heavy_check_mark: 
All linters are passing :heavy_check_mark: 

## Required Changes ♻️

- [ ] Please note that the readme file is just a template for your to create your own. :writing_hand:  Kindly make sure to customize the readme file according to your project and credentials. This applies to all your subsequent projects. :+1: 
- [ ] In accordance with standard best practices, :stuck_out_tongue_winking_eye:  please make sure to provide a summary describing introduced changes in more detail. This will help others to know what your pull request is about before delving into the project or repository. :pray: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 16:19 UTC, jerryowusu commented on .gitignore
> +node_modules
In conformity with the project requirement, kindly create a file named `test.md` and add it to the files being ignored in the .gitignore file.

2022-12-01 18:35 UTC, DuaneDave requested changes
Hi @KALUNGI-J-BOBSON 😄 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Quick implementation of requested changes 💪 
✔️ Linters are passing


 ## Required Changes ♻️
- As requested by the previous reviewer, please make your PR summary more descriptive as it pertains to this task.

for example
    - Set up linters for HTML and CSS
    - Added a CSS and HTML file etc.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 18:35 UTC, DuaneDave commented on test.md
> +This file should be ignored by git
As requested by the previous reviewer, this file should be ignored in the gitignore file. I can see that it is inside the gitignore file but it is still showing over her, kindly rectify the problem.

<img width="694" alt="tesmd" src="https://user-images.githubusercontent.com/84930355/205131508-2b750b58-ed9d-40a4-b711-88877bf1b9c4.png">

2022-12-01 18:35 UTC, DuaneDave commented on README.md
>  This project is [MIT](./LICENSE) licensed.
[OPTIONAL] Kindly add the correct path linking to your license file, each time I click on it instead of seeing your license I get a 404 page not found.

<img width="937" alt="s404" src="https://user-images.githubusercontent.com/84930355/205131939-f1d5c2e9-5ba0-4a46-b77f-7406ed202d4d.png">

2022-12-02 07:47 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @KALUNGI-J-BOBSON  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Made required changes
- Linters are passing

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 08:11 UTC, merged